### ISSUE TITLE
button B resets display on miniTFT

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_FeatherWing#56]
i think its some typo or something where we set pin 8 (TFT RST) to an input? the hardware's fine when used with arduino...
https://forums.adafruit.com/viewtopic.php?f=57&t=162744&p=800396#p800396

**Comment by makermelissa** [comment]
I'm wondering if the issue might be not setting pin back 8 to False after resetting or something like that.

**Comment by ladyada** [comment]
it def feels like a floaty pin?

**Comment by makermelissa** [comment]
It's being set to an output at https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/blob/master/adafruit_featherwing/minitft_featherwing.py#L80, but I know there's definitely some weirdness that I've seen, but hadn't been able to pinpoint. I'll explore the reset avenue.

**Comment by ladyada** [comment]
ok can u reply to the thread?

**Comment by caternuson** [comment]
awesome sauce! nice ninja sleuthing @ladyada and thanks for the quick PR fix @makermelissa.

**Comment by Anobium** [comment]
How to apply this fix? I have the same issue of button white screening the TFT.

**Comment by makermelissa** [comment]
@Anobium you can download it under https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/releases. It should be updated in the bundle on the next release, which I think it later tonight.

**Comment by Anobium** [comment]
I am writing library for non Ardunio platform.  How would I apply?  

I am thinking I update the on-board MCU.  How ?

**Comment by makermelissa** [comment]
You can read more about how to do it here: https://learn.adafruit.com/welcome-to-circuitpython/circuitpython-libraries

**Comment by Anobium** [comment]
Assume users are using an alternative compiler and a Microchip PIC XPress board.  This is the target architecture we are build utilitising the Feathers.

How to up date on Feather TFT? Is there a method to update the on-board MCU?  [I am assuming the on-board MCU is the target to be updated]
