### ISSUE TITLE
pass ts_cs  and sd_cs as arguments

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_FeatherWing#65]
Should ts_cs be passed in as an argument like all the other pins.

https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/blob/master/adafruit_featherwing/keyboard_featherwing.py#L68

also  sd_cs
https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/blob/master/adafruit_featherwing/keyboard_featherwing.py#L75

**Comment by FoamyGuy** [comment]
Ah yes, I think it probably should pass them like the others. As-is I think it may not work with Feathers that have different pin names.

**Comment by jerryneedell** [comment]
I'll create a PR -- I have a "non-standard" board that I am using (umfreathers2) and would like to be able to use the library

**Comment by FoamyGuy** [comment]
resolved by #66
