### ISSUE TITLE
requirements.txt is missing 2 dependent libraries from the list

### ISSUE THREAD

**Issue by jwcooper** [adafruit/Adafruit_CircuitPython_FeatherWing#70]
adafruit_stmpe610: 
https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/blob/310708d38699def27b8e90a2ccb1f0c6219de7b2/adafruit_featherwing/tft_featherwing_35.py#L23

adafruit_hx8357: 
https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/blob/310708d38699def27b8e90a2ccb1f0c6219de7b2/adafruit_featherwing/tft_featherwing.py#L22

This was noticed while trying to run the following tutorial code:
https://learn.adafruit.com/touch-deck-diy-tft-customized-control-pad/code-the-touch-deck
https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/CircuitPython_Touch_Deck/code.py#L14

**Comment by makermelissa** [comment]
I noticed it was also missing the ili9341 and st7735r libraries.
