### ISSUE TITLE
Library uses short argument names

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_FeatherWing#78]
`pylint` suggests using argument names with at least 3 letters.  This library uses argument names of shorter length, and while these warnings have been disabled for now, they should be considered for renaming.  This may require the rework of Learn Guides and other references to code snippets.

**Comment by makermelissa** [comment]
I'm not aware of any learn guides using this, but it would make sense to add `_pin` to most of the names.

**Comment by makermelissa** [comment]
When I added the V2 support, I added _pin where it wouldn't break compatibility, so most of this is now done.

**Comment by tekktrik** [comment]
Does it make sense to close this now then?

**Comment by DJDevon3** [comment]
or now with 9.0 just released?  Seems most of this was cleaned up by Melissa [in this commit](https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/commit/ef57c4ca35ef2f06d49ee965528b6b528fad8e45) a long time ago.

**Comment by tekktrik** [comment]
The only remaining disables I see are here:  https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/blob/97477346e41100bc97571c3e4cc36647e152d936/adafruit_featherwing/minitft_featherwing.py#L66-L67

@makermelissa are these compatibility breaking?  Not sure if you had used examples or Learn Guides to benchmark that.  I'm also fine with say this is good for now if changing these couple isn't advisable.

It's also worth mentioning that with the current discussion around switching to the ruff linter and formatter, this would also be affected (or possibly ignored).

**Comment by makermelissa** [comment]
> @makermelissa are these compatibility breaking? Not sure if you had used examples or Learn Guides to benchmark that. I'm also fine with say this is good for now if changing these couple isn't advisable.

Possibly. It depends on whether somebody has used these as a keyword argument. I'm not aware of any code I made that did theat, but I can't vouch for other folks.
